name: air-quality-batch-inference

on:
  schedule:
    - cron: "30 7 * * *"   # daily at 07:30 UTC (after features are updated)
  workflow_dispatch:      

jobs:
  batch-inference:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - name: run batch inference pipeline
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
          HOPSWORKS_PROJECT: ${{ secrets.HOPSWORKS_PROJECT }}
        # run: python scripts/run_feature_pipeline.py
        run: |
            cd pipelines
            jupyter nbconvert --to notebook --execute 4_batch_inference_pipeline.ipynb